services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped

  searxng:
    image: searxng/searxng:2026.3.10-8b95b2058
    container_name: searxng
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./searxng:/etc/searxng
    environment:
      - SEARXNG_BASE_URL=${SEARXNG_BASE_URL}
    depends_on:
      - redis

  cloudflared:
    image: cloudflare/cloudflared:2026.3.0
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - searxng
